name: StormDesk Builds
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: x86_64-pc-windows-msvc
      - name: Build
        run: cargo build --release
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: stormdesk-windows
          path: target/release/*.exe
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: x86_64-unknown-linux-gnu
      - name: Deps
        run: sudo apt-get update && sudo apt-get install -y libx11-dev libxtst-dev libxcb1-dev libxfixes-dev libxrandr-dev libxi-dev libxext-dev libssl-dev pkg-config build-essential cmake libpipewire-0.3-dev libpulse-dev libgtk-3-dev
      - name: Build
        run: cargo build --release
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: stormdesk-linux
          path: target/release/*
  build-macos:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build
        run: cargo build --release
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: stormdesk-macos
          path: target/release/*
