name: CI Windows

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-windows:
    name: Build Windows (x86_64-pc-windows-msvc)
    runs-on: windows-2022

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install prerequisites
        run: |
          choco install -y cmake ninja nasm

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          targets: x86_64-pc-windows-msvc

      - name: Show version info
        shell: pwsh
        run: |
          rustup -V
          rustc -V
          cargo -V

      - name: Build (Release)
        run: cargo build --release --target x86_64-pc-windows-msvc

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: stormdesk-windows
          path: target/x86_64-pc-windows-msvc/release/*.exe
