name: CI Windows

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-windows:
    name: Build Windows (x86_64-pc-windows-msvc)
    runs-on: windows-2022

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          targets: x86_64-pc-windows-msvc

      - name: Show version info
        run: |
          rustc -V
          cargo -V

      - name: Build Release
        run: cargo build --release --locked --target x86_64-pc-windows-msvc

      - name: Run Tests
        run: cargo test --locked --target x86_64-pc-windows-msvc

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: stormdesk-windows
          path: target\x86_64-pc-windows-msvc\release\
