name: CI Windows

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-windows:
    name: Build Windows (x86_64-pc-windows-msvc)
    runs-on: windows-2022

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          targets: x86_64-pc-windows-msvc

      - name: Show Rust version
        run: |
          rustup -V
          cargo -V
          rustc -V

      - name: Build (disable Linux audio deps)
        run: |
          cargo build --release --target x86_64-pc-windows-msvc --no-default-features --features "use_dasp"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-windows
          path: target/x86_64-pc-windows-msvc/release/rustdesk.exe
