name: CI-Windows

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:

jobs:
  build-windows:
    name: Build StormDesk (Windows)
    runs-on: windows-2022

    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Rust
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: stable

    - name: Show Rust version
      run: |
        rustc -V
        cargo -V

    - name: Build StormDesk
      run: cargo build --release --locked --target=x86_64-pc-windows-msvc

    - name: Upload StormDesk.exe
      uses: actions/upload-artifact@v4
      with:
        name: StormDesk-Windows
        path: target/x86_64-pc-windows-msvc/release/StormDesk.exe
